name: Tests
on:
  push:
    branches:
    - pfefar/tests

jobs:
  build-package-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: addnab/docker-run-action@v3
        env:
          ADMIN_API_KEY: admin_key
          BUYER_API_KEY: buyer_key
          REGISTRY: ghcr.io
          IMAGE_NAME: "atbash-labs/enclave-test"
        ports:
          - 8080
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: gcr.io
          image: enclave-test:latest
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest