name: Tests
on:
  push:
    branches:
    - pfefar/tests

jobs:
  run-image:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/atbash-labs/enclave-test:latest
      env:
        ADMIN_API_KEY: admin_key
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
  build-and-test-package:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest