name: Tests
on:
  push:
    paths:
      - 'fortress_sdk/**'
      - 'tests/**'
      - '.github/workflows/tests.yml'

jobs:
  build-package-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          docker run -d -t -e ADMIN_API_KEY="admin_key" -e SELLER_API_KEY="seller_key" -e BUYER_API_KEY="buyer_key" -p 8080:8080 ghcr.io/atbash-labs/enclave-test
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: install fortress sdk
        run: |
          pip install -e .
          sleep 2m
      - name: Test with pytest
        run: pytest 
