name: Tests
on:
  push:
    branches:
    - pfefar/tests

jobs:
  registry-login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        env:
        REGISTRY: ghcr.io
        IMAGE_NAME: "atbash-labs/enclave-test"
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-package-and-run-tests:
    runs-on: ubuntu-latest
    needs: registry-login
    container:
      image: ghcr.io/atbash-labs/enclave-test:latest
      env:
        ADMIN_API_KEY: admin_key
        BUYER_API_KEY: buyer_key
        REGISTRY: ghcr.io
        IMAGE_NAME: "atbash-labs/enclave-test"
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest